### ISSUE TITLE
道友，两个小问题

### ISSUE THREAD

**Issue by Jinxiansen** [Fnoz/FNMatchPull#1]
第一，这3张gif好歹压缩一下啊卧槽居然15M，
第二，暂时还识别不了汉字啊。

**Comment by Fnoz** [comment]
1. 我错了T.T，我只想看着清晰点，晚上回去处理一下；
2. 其实我是只是把每个字母变成几根线来实现的，所以只能识别有限的我增加的字符，不然太难了；

**Comment by Jinxiansen** [comment]
😂😂😂
